### ISSUE TITLE
how to set client secret into aquireToken method that uses username and password

### ISSUE THREAD

**Issue by user210182** [Azure-Samples/active-directory-java-native-headless#10]
Hi,
I am trying to authenticate using username and password to an application i have registered on Azure portal.
But i get the below error.
The request body must contain the following parameter: 'client_secret or client_assertion.

How can i pass the client secret using the method aquiretoken with username and password.
There is no such method in the library.

Thanks,

**Comment by ghost** [comment]
Hi,

You should configure your application as described here :

https://stackoverflow.com/questions/40858689/error-descriptionaadsts70002-the-request-body-must-contain-the-following-pa?rq=1

**Comment by TiagoBrenck** [comment]
This sample has been archived.

The newer one can be found at: https://github.com/Azure-Samples/ms-identity-java-desktop/tree/master/Username-Password-Flow
