### ISSUE TITLE
Authenticate to Azure AD non interactively in Java

### ISSUE THREAD

**Issue by ghost** [Azure-Samples/active-directory-java-native-headless#14]
Hi,

I want to authenticate to Azure AD and get bearer token. I want to do it in JAVA and NON-INTERACTIVELY

This is probably the same thing: https://azure.microsoft.com/en-us/resources/samples/active-directory-dotnet-native-headless/ - but its in dotnet

I followed, https://github.com/Azure-Samples/active-directory-java-native-headless but it it interactive and also does not work for multi factor authentication.

Can someone point me to the correct instructions?

Thanks

**Comment by sangonzal** [comment]
@Anon11123 the active-directory-java-native-headless sample is non-interactive and in Java. You are right in that it does not work for multi factor authentication (but neither does the .NET sample) What do you mean by it "it is interactive"?

**Comment by TiagoBrenck** [comment]
This sample has been archived.

The newer one can be found at: https://github.com/Azure-Samples/ms-identity-java-desktop/tree/master/Username-Password-Flow
