### ISSUE TITLE
Authenticate to Azure AD fails with access denied

### ISSUE THREAD

**Issue by mihaileb** [Azure-Samples/active-directory-java-native-headless#16]
Hello,
Using the application https://github.com/Azure-Samples/active-directory-java-native-headless we run into the error :Server returned error in RSTR - ErrorCode: FailedAuthentication : FaultMessage: MSIS7068: Access denied. 
The authentication is working fine using the native desktop dot net application with the same properties.
Can anybody provide a feedback?
Thank you,
Bruno.

**Comment by sangonzal** [comment]
@mihaileb have you followed all of the instructions listed on the README.md? If so, could you post a trace with the error message?
