### ISSUE TITLE
The documentation should describe the require change to get the token

### ISSUE THREAD

**Issue by gabriel-rcpereira** [Azure-Samples/active-directory-java-native-headless#18]
The `AUTHORITY` value should be changed to replace the `common` value for Tenant ID.

**Comment by sangonzal** [comment]
@gabriel-rcpereira The sample should work with the common endpoint ("https://login.microsoftonline.com/common/"). You don't have to (although you can if you want) replace "common" with your tenant id. Is that not the case for you?

**Comment by gabriel-rcpereira** [comment]
@sangonzal Yes, it was my case but the README doesn't describe this detail. I opened a [PR](https://github.com/Azure-Samples/active-directory-java-native-headless/pull/19) to help other developers.

**Comment by gabriel-rcpereira** [comment]
@sangonzal Now I understood what you mean. That approach didn't work for me, what did I wrong ? I could complete the flow to get the token only after I switched the `common` resource by `<tenant id>`.

**Comment by sangonzal** [comment]
@gabriel-rcpereira What was the error that you got when you tried using common?

**Comment by gabriel-rcpereira** [comment]
I'm closing the issue. The time expired.
