### ISSUE TITLE
Fail to run the sample, due to error: NullPointerException, policy is null in WSTrustRequest.execute.

### ISSUE THREAD

**Issue by Lambert2017** [Azure-Samples/active-directory-java-native-headless#3]
I would like to develop an app with raw username and password authentication.

But I failed to run this sample, and met with a  java.lang.NullPointerException. 
I debugged the code and found that this happened at:
      if (policy.getVersion() == WSTrustVersion.WSTRUST2005) {
            soapAction = "http://schemas.xmlsoap.org/ws/2005/02/trust/RST/Issue"; // wsTrust2005
                                                                                  // soap
                                                                                  // value
         }

policy value is null, thus throws exception.

Please help guide me to run this sample successfully. 

The error msg is listed as below:

lambert@lambert-Lenovo-PC:~/active-directory-java-native-headless/target$ java -jar public-client-adal4j-sample-jar-with-dependencies.jar 
Enter username: lamberttest2017@outlook.com
Enter password: Lambert2017
log4j:WARN No appenders could be found for logger (com.microsoft.aad.adal4j.UserDiscoveryRequest).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
Exception in thread "main" java.util.concurrent.ExecutionException: java.lang.NullPointerException
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at PublicClient.getAccessTokenFromUserCredentials(PublicClient.java:48)
	at PublicClient.main(PublicClient.java:26)
Caused by: java.lang.NullPointerException
	at com.microsoft.aad.adal4j.WSTrustRequest.execute(WSTrustRequest.java:62)
	at com.microsoft.aad.adal4j.AuthenticationContext.processPasswordGrant(AuthenticationContext.java:841)
	at com.microsoft.aad.adal4j.AuthenticationContext.access$000(AuthenticationContext.java:66)
	at com.microsoft.aad.adal4j.AuthenticationContext$1.call(AuthenticationContext.java:173)
	at com.microsoft.aad.adal4j.AuthenticationContext$1.call(AuthenticationContext.java:163)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by Slmba** [comment]
same issue. is somebody here?

**Comment by pekour** [comment]
The same for me. https://nexus.passport.com/FederationMetadata/2007-06/FederationMetadata.xml is just not containing the searched policies. Is this lib still supported?

**Comment by pekour** [comment]
I found a reason for that. When you try to log in using federated account (like your domain is xxx.onmicrosoft.com and you log in as yyy@outlook.com), library fails with NPE. But when you use native account, it gives token as expected.

**Comment by anotherrohit** [comment]
@pekour How can I get my native account for the application? I get federated to Azure at login tot he dashboard everytime. Can you please let me know how i can get a native account to make the access token work.

**Comment by pekour** [comment]
@anotherrohit , just create your users in your domain. In the menu use Azure Active Directory -> Users and groups -> All users -> New user etc. This user will be able to log in via ADAL

**Comment by anotherrohit** [comment]
@pekour I am unable to create user natively thru user and groups > all users due to the error the domain name to chose should be non federated for a user to be created. How do I even create a non federated domain? Do I have a register a new domain thru azure in addition to the one I already have on godaddy?

**Comment by navyasric** [comment]
Sorry for the delayed response. ADAL4J supports authentication with Azure AD and ADFS user accounts only. Please follow these guides to [create Azure AD tenant](https://docs.microsoft.com/en-us/azure/active-directory/develop/active-directory-howto-tenant#create-a-new-azure-ad-tenant), [create custom domains](https://docs.microsoft.com/en-us/azure/active-directory/add-custom-domain) and [add users](https://docs.microsoft.com/en-us/azure/active-directory/add-users-azure-active-directory). 

Closing for now. Please reopen if needed.

**Comment by msfcolombo** [comment]
Error message should be fixed. "null pointer exception" has nothing to do with "federated accounts are not supported".
