### ISSUE TITLE
Error: Interaction required

### ISSUE THREAD

**Issue by venkatmarepalli** [Azure-Samples/active-directory-java-native-headless#4]
I tried your application on windows and it worked like a charm, I was wondering if this ADAL library can bypass MFA or not. 

Our organization has MFA setup, it asks for MFA whenever a user logs in from a different location. When I tried this sample on my Linux box which is at a different location, I got the below error.  Please confirm if ADAL library can bypass MFA and give users text only interface to authenticate to the application.

`Caused by: com.microsoft.aad.adal4j.AuthenticationException: {"error":"interaction_required","error_description":"AADSTS50076: Due to a configuration change made by your administrator, or because you moved to a new location, you must use multi-factor authentication to access '00000002-0000-0000-c000-000000000000'.\r\nTrace ID: 7903cd61-659e-4dc6-a8b0-3dac4c672700\r\nCorrelation ID: b541777f-e2cc-4b87-ab7b-8dd83654d445\r\nTimestamp: 2017-04-18 23:02:36Z"}`

**Comment by sangonzal** [comment]
Hi @venkatmarepalli, ADAL4J can be used to sign in MFA enabled accounts, although this sample does not show how to do it. If you'd like to see a sample that handles MFA, take a look at this [web app sample](https://github.com/AzureAD/azure-activedirectory-library-for-java/tree/dev/src/samples).

**Comment by venkatmarepalli** [comment]
Thank you for your reply.  Can you tell me how MFA is handled here? Does it make users to enter the code on console or does ADALJ4 passes authentication without MFA ? 

@sangonzal Just to clarify we have a native app which does authentication using the browser, we wanted to get rid off this process if ADALJ4 supports MFA or this [feature ](https://feedback.azure.com/forums/169401-azure-active-directory/suggestions/13817784-add-support-for-resource-owner-password-credential?tracking_code=376d48e3450d06a1df2c221b3ad30260)is released

**Comment by user210182** [comment]
Hi,
I am trying to authenticate using username and password to an application i have registered on Azure portal.
But i get the below error.
 The request body must contain the following parameter: 'client_secret or client_assertion.

How can i pass the client secret using the method aquiretoken with username and password.
There is no such method in the library.

Thanks,

**Comment by TiagoBrenck** [comment]
This sample has been archived.

The newer one can be found at: https://github.com/Azure-Samples/ms-identity-java-desktop/tree/master/Username-Password-Flow
