### ISSUE TITLE
400 error from IdP

### ISSUE THREAD

**Issue by anotherrohit** [Azure-Samples/active-directory-java-native-headless#6]
I get Exception in thread "main" java.util.concurrent.ExecutionException: java.io.IOException: Server returned HTTP response code: 400 for URL: https://sso.godaddy.com/v1/wss/mex/ on interactively entering username and password. The client-id info entered is verified to be correct.
I have azure from godaddy. Any idea what is wrong here?

**Comment by jmprieur** [comment]
The client id (application id) for your application was probably not the right one.
did you register the application?

**Comment by jmprieur** [comment]
BTW closing this issue as the sample was updated with clear instructions on how to register the Azure AD application (or even scripts to do that)
